apiVersion: v1
kind: Namespace
metadata:
  name: nsfw-api
  labels:
    name: nsfw-api
---
apiVersion: v1
kind: Service
metadata:
  name: nsfw-api
  namespace: nsfw-api
  labels:
    app: nsfw-api
spec:
  ports:
    - port: 8000
  selector:
    app: nsfw-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsfw-api
  namespace: nsfw-api
  labels:
    app: nsfw-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nsfw-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nsfw-api
    spec:
      containers:
      - image: museaqours/nsfw-api:latest
        name: nsfw-api
        ports:
        - containerPort: 8000
          name: nsfw-api
        readinessProbe:
          httpGet:
            path: /predict
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 3
        resources:
          requests:
            memory: "1.5Gi"
          limits:
            memory: "1.5Gi"
